### ISSUE TITLE
Consider adding `wait_timeout` interface

### ISSUE THREAD

**Issue by sr-gi** [faern/triggered#2]
It'll be nice to have a `wait_timeout` interface so the `Listener` could be waited up to a certain timeout analogously to how `Condvar::wait_timeout` works. 

The main rationale behind this request is to be able to perform some tasks every fixed period of time, but be able to stop waiting as soon as the shutdown signal is received.

Kind of turning:

```
// This needs to wait timeout secs to check if the listener has been triggered

if listener.is_triggered() {
         return;
} else {
        thread::sleep(timeout);
}
```

Into:

```
// This can return as soon as listener it's triggered

listener.wait_timeout(timeout)
if listener.is_triggered() {
        return;
}
```

`wait_timeout` could even return whether `Listener` has been triggered or it has timed-out, in the same way `Condvar::wait_timeout` does.

**Comment by faern** [comment]
In an async program you would just do that by wrapping the `Listener` in one of the various `Timeout` types that exists. For sync code I guess this new method could be handy. Underneath the hood `Listener::wait` is using a condvar, and condvars have `wait_timeout`. So should probably not be very hard to implement.

@sr-gi Would you please have a look at #3 and see if it fits your needs and if you think the code looks correct?
